[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
